language: go

go:
- 1.10.x

env:
- POSTGRESQL_IMAGE=postgres

services:
- docker

go_import_path: github.com/percona/postgres_exporter

before_script:
- sudo service postgresql stop
- docker --version
- docker-compose --version
- docker-compose up -d

script:
- make
- make test

notifications:
  email: false
